//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrectPositionAndColorsClue
    {
        public int correct_position_and_colors_id { get; set; }
        public int position { get; set; }
        public int clue_color_id { get; set; }
    
        public virtual ClueColorsCatalog ClueColorsCatalog { get; set; }
        public virtual CorrectPositionAndColors CorrectPositionAndColors { get; set; }
    }
}
