//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecipherTry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DecipherTry()
        {
            this.DecipherTryCode = new HashSet<DecipherTryCode>();
        }
    
        public int decipher_try_id { get; set; }
        public int match_room_id { get; set; }
        public int player_id { get; set; }
        public Nullable<int> attempt_number { get; set; }
    
        public virtual CorrectPositionAndColors CorrectPositionAndColors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecipherTryCode> DecipherTryCode { get; set; }
        public virtual MatchRoom MatchRoom { get; set; }
        public virtual Player Player { get; set; }
    }
}
