//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int friendship_id { get; set; }
        public int requester_id { get; set; }
        public int addressee_id { get; set; }
        public int status_id { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual RequestStatusCatalog RequestStatusCatalog { get; set; }
    }
}
