//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterMindEntities : DbContext
    {
        public MasterMindEntities()
            : base("name=MasterMindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClueColorsCatalog> ClueColorsCatalog { get; set; }
        public virtual DbSet<CodeColorsCatalog> CodeColorsCatalog { get; set; }
        public virtual DbSet<CorrectPositionAndColors> CorrectPositionAndColors { get; set; }
        public virtual DbSet<CorrectPositionAndColorsClue> CorrectPositionAndColorsClue { get; set; }
        public virtual DbSet<DecipherTry> DecipherTry { get; set; }
        public virtual DbSet<DecipherTryCode> DecipherTryCode { get; set; }
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<GameInvitation> GameInvitation { get; set; }
        public virtual DbSet<GameModesCatalog> GameModesCatalog { get; set; }
        public virtual DbSet<MatchResults> MatchResults { get; set; }
        public virtual DbSet<MatchRoom> MatchRoom { get; set; }
        public virtual DbSet<MatchRoomSecretCode> MatchRoomSecretCode { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayerInMatch> PlayerInMatch { get; set; }
        public virtual DbSet<PlayerReport> PlayerReport { get; set; }
        public virtual DbSet<PlayerTimeTrialRecords> PlayerTimeTrialRecords { get; set; }
        public virtual DbSet<PlayerTriesRecords> PlayerTriesRecords { get; set; }
        public virtual DbSet<ReportReasonCatalog> ReportReasonCatalog { get; set; }
        public virtual DbSet<RequestStatusCatalog> RequestStatusCatalog { get; set; }
        public virtual DbSet<RoundsTimeResults> RoundsTimeResults { get; set; }
        public virtual DbSet<RoundsTriesResults> RoundsTriesResults { get; set; }
        public virtual DbSet<TimeTrialConfig> TimeTrialConfig { get; set; }
        public virtual DbSet<TriesConfig> TriesConfig { get; set; }
        public virtual DbSet<VerificationCode> VerificationCode { get; set; }
    }
}
