//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchRoomSecretCode
    {
        public int position { get; set; }
        public int match_room_id { get; set; }
        public int color_id { get; set; }
    
        public virtual CodeColorsCatalog CodeColorsCatalog { get; set; }
        public virtual MatchRoom MatchRoom { get; set; }
    }
}
