//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatchRoom()
        {
            this.DecipherTry = new HashSet<DecipherTry>();
            this.GameInvitation = new HashSet<GameInvitation>();
            this.MatchResults = new HashSet<MatchResults>();
            this.MatchRoomSecretCode = new HashSet<MatchRoomSecretCode>();
        }
    
        public int match_room_id { get; set; }
        public int gamemode_id { get; set; }
        public int player_one_id { get; set; }
        public int player_two_id { get; set; }
        public string private_room_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecipherTry> DecipherTry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameInvitation> GameInvitation { get; set; }
        public virtual GameModesCatalog GameModesCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchResults> MatchResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchRoomSecretCode> MatchRoomSecretCode { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual TimeTrialConfig TimeTrialConfig { get; set; }
        public virtual TriesConfig TriesConfig { get; set; }
    }
}
