//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerTriesRecords
    {
        public int records_id { get; set; }
        public int player_id { get; set; }
        public Nullable<int> tries_record { get; set; }
        public int rank { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
