//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundsTriesResults
    {
        public int rounds_tries_results_id { get; set; }
        public int player_in_match_id { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<int> tries { get; set; }
    
        public virtual PlayerInMatch PlayerInMatch { get; set; }
    }
}
