//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterMind_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de correo electrónico ingresada ya está en uso, prueba una distinta por favor.
        /// </summary>
        public static string ErrorNotification_EmailTaken {
            get {
                return ResourceManager.GetString("ErrorNotification_EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de correo debe tener un formato válido. Revisa que tenga solo un &apos;@&apos;, y que tenga una extensión válida como .com.
        /// </summary>
        public static string ErrorNotification_InvalidEmail {
            get {
                return ResourceManager.GetString("ErrorNotification_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más campos que ingresaste están campos vacíos, no debe haber ningún campo de registro vacío..
        /// </summary>
        public static string ErrorNotification_InvalidInput {
            get {
                return ResourceManager.GetString("ErrorNotification_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres, una mayúscula, una minúscula y un número.
        /// </summary>
        public static string ErrorNotification_InvalidPassword {
            get {
                return ResourceManager.GetString("ErrorNotification_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorNotification_Title {
            get {
                return ResourceManager.GetString("ErrorNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ingresado ya está en uso, prueba uno distinto por favor.
        /// </summary>
        public static string ErrorNotification_UsernameTaken {
            get {
                return ResourceManager.GetString("ErrorNotification_UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más campos que ingresaste son inválidos, revisa por favor que el formato sea correcto y que la contraseña tenga mínimo 8 caracteres, una mayúscula, una minúscula y un número.
        /// </summary>
        public static string ErrorNotification_WhiteInput {
            get {
                return ResourceManager.GetString("ErrorNotification_WhiteInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las credenciales ingresadas son incorrectas.
        /// </summary>
        public static string ErrorNotification_WrongCredentials {
            get {
                return ResourceManager.GetString("ErrorNotification_WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes una cuenta?.
        /// </summary>
        public static string LoginPage_AccountQuestion {
            get {
                return ResourceManager.GetString("LoginPage_AccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string LoginPage_Login {
            get {
                return ResourceManager.GetString("LoginPage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate.
        /// </summary>
        public static string LoginPage_SignupLink {
            get {
                return ResourceManager.GetString("LoginPage_SignupLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainPage_Friends {
            get {
                return ResourceManager.GetString("MainPage_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string MainPage_Play {
            get {
                return ResourceManager.GetString("MainPage_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string MainPage_Profile {
            get {
                return ResourceManager.GetString("MainPage_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string MainPage_Quit {
            get {
                return ResourceManager.GetString("MainPage_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Vamos a Descifrar!.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si ves este mensaje, algo salió mal. Contacta a soporte técnico..
        /// </summary>
        public static string NotificationModal_DefaultMessage {
            get {
                return ResourceManager.GetString("NotificationModal_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Player_Email {
            get {
                return ResourceManager.GetString("Player_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Player_Password {
            get {
                return ResourceManager.GetString("Player_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Player_Username {
            get {
                return ResourceManager.GetString("Player_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta?.
        /// </summary>
        public static string SignupPage_AccountQuestion {
            get {
                return ResourceManager.GetString("SignupPage_AccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string SignupPage_LoginLink {
            get {
                return ResourceManager.GetString("SignupPage_LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string SignupPage_Register {
            get {
                return ResourceManager.GetString("SignupPage_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string SignupPage_Title {
            get {
                return ResourceManager.GetString("SignupPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Tu cuenta fue registrada con éxito! Se envió un correo de verificación a tu correo.
        /// </summary>
        public static string SuccessNotification_Register {
            get {
                return ResourceManager.GetString("SuccessNotification_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Éxito!.
        /// </summary>
        public static string SuccessNotification_Title {
            get {
                return ResourceManager.GetString("SuccessNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string UI_Continue {
            get {
                return ResourceManager.GetString("UI_Continue", resourceCulture);
            }
        }
    }
}
