//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMind_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterMind_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad.
        /// </summary>
        public static string CreateRoomPage_Difficulty {
            get {
                return ResourceManager.GetString("CreateRoomPage_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de juego.
        /// </summary>
        public static string CreateRoomPage_Mode {
            get {
                return ResourceManager.GetString("CreateRoomPage_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la Sala.
        /// </summary>
        public static string CreateRoomPage_Name {
            get {
                return ResourceManager.GetString("CreateRoomPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacidad de Sala.
        /// </summary>
        public static string CreateRoomPage_Privacy {
            get {
                return ResourceManager.GetString("CreateRoomPage_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una Sala.
        /// </summary>
        public static string CreateRoomPage_Title {
            get {
                return ResourceManager.GetString("CreateRoomPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de correo electrónico ingresada ya está en uso, prueba una distinta por favor.
        /// </summary>
        public static string ErrorNotification_EmailTaken {
            get {
                return ResourceManager.GetString("ErrorNotification_EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error al enviar la solicitud de amistad. Intenta de nuevo más tarde.
        /// </summary>
        public static string ErrorNotification_ErrorSendingFriendRequest {
            get {
                return ResourceManager.GetString("ErrorNotification_ErrorSendingFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de amistad enviada a este jugador está en espera de ser aceptada.
        /// </summary>
        public static string ErrorNotification_FriendRequestPending {
            get {
                return ResourceManager.GetString("ErrorNotification_FriendRequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de correo debe tener un formato válido. Revisa que tenga solo un &apos;@&apos;, y que tenga una extensión válida como .com.
        /// </summary>
        public static string ErrorNotification_InvalidEmail {
            get {
                return ResourceManager.GetString("ErrorNotification_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más campos que ingresaste están campos vacíos, no debe haber ningún campo de registro vacío..
        /// </summary>
        public static string ErrorNotification_InvalidInput {
            get {
                return ResourceManager.GetString("ErrorNotification_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres, una mayúscula, una minúscula y un número.
        /// </summary>
        public static string ErrorNotification_InvalidPassword {
            get {
                return ResourceManager.GetString("ErrorNotification_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorNotification_Title {
            get {
                return ResourceManager.GetString("ErrorNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ingresado ya está en uso, prueba uno distinto por favor.
        /// </summary>
        public static string ErrorNotification_UsernameTaken {
            get {
                return ResourceManager.GetString("ErrorNotification_UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más campos que ingresaste son inválidos, revisa por favor que el formato sea correcto y que la contraseña tenga mínimo 8 caracteres, una mayúscula, una minúscula y un número.
        /// </summary>
        public static string ErrorNotification_WhiteInput {
            get {
                return ResourceManager.GetString("ErrorNotification_WhiteInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación ingresado es incorrecto, intenta de nuevo..
        /// </summary>
        public static string ErrorNotification_WrongCode {
            get {
                return ResourceManager.GetString("ErrorNotification_WrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las credenciales ingresadas son incorrectas.
        /// </summary>
        public static string ErrorNotification_WrongCredentials {
            get {
                return ResourceManager.GetString("ErrorNotification_WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar un nuevo amigo.
        /// </summary>
        public static string FriendRequestsModal_AddFriendText {
            get {
                return ResourceManager.GetString("FriendRequestsModal_AddFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes de amistad.
        /// </summary>
        public static string FriendRequestsModal_Title {
            get {
                return ResourceManager.GetString("FriendRequestsModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string FriendsModal_Title {
            get {
                return ResourceManager.GetString("FriendsModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fácil.
        /// </summary>
        public static string GameDifficulty_Easy {
            get {
                return ResourceManager.GetString("GameDifficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enigma.
        /// </summary>
        public static string GameDifficulty_Enigma {
            get {
                return ResourceManager.GetString("GameDifficulty_Enigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difícil.
        /// </summary>
        public static string GameDifficulty_Hard {
            get {
                return ResourceManager.GetString("GameDifficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string GameDifficulty_Normal {
            get {
                return ResourceManager.GetString("GameDifficulty_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrarreloj.
        /// </summary>
        public static string Gamemode_TimeTrial {
            get {
                return ResourceManager.GetString("Gamemode_TimeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos.
        /// </summary>
        public static string Gamemode_Tries {
            get {
                return ResourceManager.GetString("Gamemode_Tries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin del Juego.
        /// </summary>
        public static string GameOverModal_GameOver {
            get {
                return ResourceManager.GetString("GameOverModal_GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Se acabó el Tiempo!.
        /// </summary>
        public static string GameOverTimeTrialModal_Title {
            get {
                return ResourceManager.GetString("GameOverTimeTrialModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Te quedaste sin intentos!.
        /// </summary>
        public static string GameOverTriesModal_Title {
            get {
                return ResourceManager.GetString("GameOverTriesModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes una cuenta?.
        /// </summary>
        public static string LoginPage_AccountQuestion {
            get {
                return ResourceManager.GetString("LoginPage_AccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string LoginPage_Login {
            get {
                return ResourceManager.GetString("LoginPage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate.
        /// </summary>
        public static string LoginPage_SignupLink {
            get {
                return ResourceManager.GetString("LoginPage_SignupLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainPage_Friends {
            get {
                return ResourceManager.GetString("MainPage_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string MainPage_Play {
            get {
                return ResourceManager.GetString("MainPage_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string MainPage_Profile {
            get {
                return ResourceManager.GetString("MainPage_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string MainPage_Quit {
            get {
                return ResourceManager.GetString("MainPage_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Vamos a Descifrar!.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu nueva contraseña.
        /// </summary>
        public static string NewPasswordModal_Title {
            get {
                return ResourceManager.GetString("NewPasswordModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si ves este mensaje, algo salió mal. Contacta a soporte técnico..
        /// </summary>
        public static string NotificationModal_DefaultMessage {
            get {
                return ResourceManager.GetString("NotificationModal_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Player_Email {
            get {
                return ResourceManager.GetString("Player_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Player_Password {
            get {
                return ResourceManager.GetString("Player_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Player_Username {
            get {
                return ResourceManager.GetString("Player_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string PrivateRoomCodeModal_Join {
            get {
                return ResourceManager.GetString("PrivateRoomCodeModal_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el Código de la Sala.
        /// </summary>
        public static string PrivateRoomCodeModal_Title {
            get {
                return ResourceManager.GetString("PrivateRoomCodeModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor Tiempo: .
        /// </summary>
        public static string ProfilePage_BestTime {
            get {
                return ResourceManager.GetString("ProfilePage_BestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string ProfilePage_ChangePassword {
            get {
                return ResourceManager.GetString("ProfilePage_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menos Intentos: .
        /// </summary>
        public static string ProfilePage_LeastTries {
            get {
                return ResourceManager.GetString("ProfilePage_LeastTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Records.
        /// </summary>
        public static string ProfilePage_Records {
            get {
                return ResourceManager.GetString("ProfilePage_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar a un jugador.
        /// </summary>
        public static string ProfilePage_ReportPlayer {
            get {
                return ResourceManager.GetString("ProfilePage_ReportPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  seg..
        /// </summary>
        public static string ProfilePage_Seconds {
            get {
                return ResourceManager.GetString("ProfilePage_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string ProfilePage_Update {
            get {
                return ResourceManager.GetString("ProfilePage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string RoomPage_Chat {
            get {
                return ResourceManager.GetString("RoomPage_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decifradores.
        /// </summary>
        public static string RoomPage_Deciphers {
            get {
                return ResourceManager.GetString("RoomPage_Deciphers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string RoomPage_Ready {
            get {
                return ResourceManager.GetString("RoomPage_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string RoomPage_Room {
            get {
                return ResourceManager.GetString("RoomPage_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string RoomPage_Unready {
            get {
                return ResourceManager.GetString("RoomPage_Unready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privada.
        /// </summary>
        public static string RoomPrivacy_Private {
            get {
                return ResourceManager.GetString("RoomPrivacy_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pública.
        /// </summary>
        public static string RoomPrivacy_Public {
            get {
                return ResourceManager.GetString("RoomPrivacy_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string RoomsPage_Code {
            get {
                return ResourceManager.GetString("RoomsPage_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string RoomsPage_Create {
            get {
                return ResourceManager.GetString("RoomsPage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string RoomsPage_Join {
            get {
                return ResourceManager.GetString("RoomsPage_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string RoomsPage_Refresh {
            get {
                return ResourceManager.GetString("RoomsPage_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salas de deciframiento.
        /// </summary>
        public static string RoomsPage_Title {
            get {
                return ResourceManager.GetString("RoomsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta?.
        /// </summary>
        public static string SignupPage_AccountQuestion {
            get {
                return ResourceManager.GetString("SignupPage_AccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string SignupPage_LoginLink {
            get {
                return ResourceManager.GetString("SignupPage_LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string SignupPage_Register {
            get {
                return ResourceManager.GetString("SignupPage_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string SignupPage_Title {
            get {
                return ResourceManager.GetString("SignupPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡La solicitud de amistad fue enviada con éxito!.
        /// </summary>
        public static string SuccessNotification_FriendRequestSent {
            get {
                return ResourceManager.GetString("SuccessNotification_FriendRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Tu cuenta fue registrada con éxito! Se envió un código de verificación a tu correo.
        /// </summary>
        public static string SuccessNotification_Register {
            get {
                return ResourceManager.GetString("SuccessNotification_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Éxito!.
        /// </summary>
        public static string SuccessNotification_Title {
            get {
                return ResourceManager.GetString("SuccessNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string UI_Accept {
            get {
                return ResourceManager.GetString("UI_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string UI_Back {
            get {
                return ResourceManager.GetString("UI_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string UI_Cancel {
            get {
                return ResourceManager.GetString("UI_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string UI_Close {
            get {
                return ResourceManager.GetString("UI_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string UI_Continue {
            get {
                return ResourceManager.GetString("UI_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string UI_Create {
            get {
                return ResourceManager.GetString("UI_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escapar.
        /// </summary>
        public static string UI_Escape {
            get {
                return ResourceManager.GetString("UI_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string UpdateProfilePage_Save {
            get {
                return ResourceManager.GetString("UpdateProfilePage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código de verificación.
        /// </summary>
        public static string VerificationCodeModal_ResendCode {
            get {
                return ResourceManager.GetString("VerificationCodeModal_ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el código de verificación.
        /// </summary>
        public static string VerificationCodeModal_Title {
            get {
                return ResourceManager.GetString("VerificationCodeModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ganaste!.
        /// </summary>
        public static string YouWonModal_Title {
            get {
                return ResourceManager.GetString("YouWonModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Código Secreto era:.
        /// </summary>
        public static string YouWonTriesModal_SecretCode {
            get {
                return ResourceManager.GetString("YouWonTriesModal_SecretCode", resourceCulture);
            }
        }
    }
}
